FROM python:3.11.2

# install dependencies
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# copy the rest of the files
COPY temp_sensors.py /app/temp_sensors.py
COPY utils.py /app/utils.py
COPY .env /app/.env

CMD ["python", "temp_sensors.py"]
