FROM python:3.11.2

# install dependencies
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# copy the rest of the files
COPY mavlink.py /app/mavlink.py
COPY utils.py /app/utils.py
COPY .env /app/.env

CMD ["python", "mavlink.py"]