services:
  redis:
    restart: unless-stopped
    image: redis:7.4-rc2
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    networks:
      - mavlink-network

  mavlink-router:
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.mavlink_router
    ports:
      - 5760:5760
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/ttyACM0:/dev/ttyACM0
    networks:
      - mavlink-network

  mavlink-sensor:
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.mavlink_sensor
    depends_on:
      - redis
      - mavlink-router
    environment:
      - REDIS_HOST=redis
      - MAVLINK_ROUTER_HOST=mavlink-router
      - MAVLINK_ROUTER_PORT=5760
      - FC_SYSID=213
    networks:
      - mavlink-network

  gas-sensors:
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.gas_sensors
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - GAS_BUFFER_SIZE=6
      - SENSOR_ANALOG_VALUE_MAX=65536
    networks:
      - mavlink-network

  temp-sensors:
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.temp_sensor
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - TEMP_OUTLIER_CUTOFF=3
      - TEMP_REFRESH_RATE=5
      - TEMP_EXPIRE=15
      - TEMP_BUFFER_SIZE=10
    networks:
      - mavlink-network

networks:
  mavlink-network:
    driver: bridge
