services:
  redis:
    restart: unless-stopped
    image: redis:7.4-rc2
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    networks:
      - mavlink-network

  mavlink_sensor:
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.mavlink_sensor
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - FC_SYSID=213
    networks:
      - mavlink-network

  gas_sensors:
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.gas_sensors
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - mavlink-network

  temp_humid_sensors:
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.temp_humid_sensors
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - mavlink-network

networks:
  mavlink-network:
    driver: bridge
