FROM python:3.11.2

# install dependencies
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# copy the rest of the files
COPY gas_sensors.py /app/gas_sensors.py
COPY utils.py /app/utils.py
COPY mq135.py /app/mq135.py
COPY .env /app/.env

CMD ["python", "gas_sensors.py"]